version: "3"

services:
  redis:
    image: "redis:latest"
    environment:
      REDIS_ADDR: "redis:6379"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "knoxsdating"
      POSTGRES_USER: "knoxs"
      POSTGRES_PASSWORD: "knoxsdating"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  migration:
    image: "flyway/flyway:latest"
    command: ["migrate"]
    depends_on:
      - postgres
    volumes:
      - ./flyway:/flyway/sql
      - ./flyway.conf:/flyway/conf/flyway.conf

  app1:
    build:
      context: .
    environment:
      REDIS_ADDR: "redis:6379"
      POSTGRES_ADDR: "postgres:5432"
      PORT: "8080"
    expose:
      - "8080"
    depends_on:
      - postgres
      - redis

  app2:
    build:
      context: .
    environment:
      REDIS_ADDR: "redis:6379"
      POSTGRES_ADDR: "postgres:5432"
      PORT: "8081"
    expose:
      - "8081"
    depends_on:
      - postgres
      - redis

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
